language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.31.0
sudo: false
os:
  - linux
cache:
  directories:
    - $TRAVIS_BUILD_DIR/target
    - $HOME/.cargo

script:
  - cargo test --all-features -- --ignored
